server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # POS 서비스 라우팅
        - id: pos-service
          uri: lb://pay-pos-service
          predicates:
            - Path=/api/v1/approval/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
