server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # POS 서비스 라우팅
        - id: pos-service
          uri: lb://pay-pos-service
          predicates:
            - Path=/api/v1/approval/**
